单测规范化建设
PaddlePaddle/PaConvert pull request #439
Opened 2024-07-30 15:09 UTC by Xuxuanang

### PR Docs
算子单测规范化建设

### PR APIs

torch.BFloat16Tensor	
torch.Tensor.ceil
torch.Tensor.eq_
torch.Tensor.expand
torch.Tensor.floor_
torch.Tensor.greater_
torch.Tensor.greater_equal_
torch.Tensor.less_
torch.Tensor.less_equal_
torch.Tensor.not_equal_
torch.Tensor.square_	
torch.Tensor.symeig
torch.__version__.split
```bash

```

2024-07-30 15:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaConvert?pullRequest=439) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaConvert?pullRequest=439) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaConvert?pullRequest=439) it.</sub>

2024-07-31 04:11 UTC, zhwesky2010 commented on tests/test_Bfloat16Tensor.py
> +def _test_case_1():
1. paddle支持bfloat16
2. 这里看起来并不是torch.BFloat16Tensor的调用方法

2024-07-31 04:11 UTC, zhwesky2010 commented on tests/test_Tensor_ceil.py
> +def test_case_3():
这里都是相同用法可以减少几个case，重复case意义不大

尽可能写不同调用形式的case

2024-07-31 04:11 UTC, zhwesky2010 commented on tests/test_Tensor_expand.py
> +def test_case_1():
这里虽然case很多，但全部都是同一种用法，这样意义不大。

这个API有size=、可变参数、list/tuple、可变参数解包 等不同用法，可以学习下 `torch.Tensor.reshape` 的用法

2024-07-31 04:11 UTC, zhwesky2010 commented on tests/test_Tensor_floor_.py
> +        result = torch.tensor([1.999, 2.0001, -3.999, -4.0001])
尽可能写不同形式的case，重复测试意义不大

2024-07-31 04:11 UTC, zhwesky2010 commented on tests/test_Tensor_greater_equal_.py
>  # `paddle.Tensor.cast_` has bug when continuous inplace on cpu
如果测试cast_没问题：可以删掉上面的备注：
```
# `paddle.Tensor.cast_` has bug when continuous inplace on cpu
```

2024-07-31 04:11 UTC, zhwesky2010 commented on tests/test_Tensor_symeig.py
> -        result = x.symeig(eigenvectors=False, upper=False)
这个case的修改原因？

目前最新版torch 无这个API是吗

2024-07-31 04:11 UTC, zhwesky2010 commented on tests/test_bfloat16.py
> +
移除

是不是没有安装pre-commit

2024-07-31 14:14 UTC, zhwesky2010 commented on tests/test_Bfloat16Tensor.py
> +def _test_case_1():
这个是不是得改一下Matcher的Bug

2024-07-31 14:19 UTC, Xuxuanang commented on tests/test_Bfloat16Tensor.py
> +def _test_case_1():
貌似不是吧，我看paddle的to_tensor好像并不支持bfloat16

2024-08-01 07:05 UTC, zhwesky2010 commented
@Xuxuanang 代码风格，pre-commit还是有点问题

2024-08-01 12:44 UTC, Xuxuanang commented
@zhwesky2010 已经重新提交

2024-08-02 10:03 UTC, zhwesky2010 requested changes
comment你需要逐个修改，修改完后，你标记一下mark resolved

2024-08-02 10:03 UTC, zhwesky2010 commented on tests/test_Bfloat16Tensor.py
> +def test_case_1():
参考下同类的单测：PaConvert/tests/test_FloatTensor.py，你这里的case写得不是很全 https://github.com/PaddlePaddle/PaConvert/blob/master/docs/CONTRIBUTING.md#%E6%AD%A5%E9%AA%A45%E7%BC%96%E5%86%99%E5%8D%95%E5%85%83%E6%B5%8B%E8%AF%95

要求：

```
单测覆盖范围要求为：涉及到多个API形参的，应包含各种参数用法（ 全部指定关键字、全部不指定关键字、改变关键字顺序、默认参数均不指定 四种情况必须考虑），不能只考虑最简单常见的用法，要求至少列举5种不同的使用case（越多越好）。
```

2024-08-02 10:03 UTC, zhwesky2010 commented on tests/test_Tensor_expand.py
> +def test_case_1():
这个comment没有修改

2024-08-05 08:41 UTC, zhwesky2010 commented on tests/test_Bfloat16Tensor.py
> +class Bfloat16TensorAPIBase(APIBase):
命名改一下：
`class BFloat16TensorAPIBase`
`test_BFloat16Tensor.py`

另外这里没有bfloat16 tensor的分支，也需要加一下，但这里为何没有触发到检查？按道理单测应该触发这里的分支

![infoflow 2024-08-05 16-34-58](https://github.com/user-attachments/assets/059608ce-e346-4f9f-95ff-aeef87cc78c6)

2024-08-06 13:15 UTC, zhwesky2010 commented on paconvert/api_matcher.py
> +                elif "torch.BFloat16Tensor" == self.torch_api:
`torch.cuda.BFloat16Tensor` 这个不写吗

2024-08-06 13:15 UTC, zhwesky2010 commented on paconvert/api_matcher.py
> +        elif "torch.BFloat16Tensor" == self.torch_api:
`torch.cuda.BFloat16Tensor ` 这个不写吗

2024-08-07 03:43 UTC, zhwesky2010 commented on paconvert/api_matcher.py
> +        elif ("torch.BFloat16Tensor" == self.torch_api) or (
这个分支和上面那个分支是不是用 `paddle.empty` 更合适一些，用 `paddle.zeros` 的原因是？

2024-08-08 06:26 UTC, zhwesky2010 approved these changes

2024-08-08 06:26 UTC, merged